<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Loco1.Data\Loco1.Data.csproj" />
    <ProjectReference Include="..\Loco1.Localizer\Loco1.Localizer.csproj" />
    <ProjectReference Include="..\Loco1.ViewModels\Loco1.ViewModels.csproj" />
  </ItemGroup>

</Project>
