<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Loco1.web-ffcc835e-1194-457d-8262-7606d7031807</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.23" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\" />
    <Folder Include="Areas\Identity\Data\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GCommon\GCommon.csproj" />
    <ProjectReference Include="..\Loco1.Data\Loco1.Data.csproj" />
  </ItemGroup>

</Project>
